---
:request:
  :url: http://api.alve.com/products/1135844
  :headers:
    :accept: application/vnd.alve+json; version=3.1
    :authorization: Bearer Ei3DkEzs/gQSMk8EW8mPBJEyYPCliK7bvq1KhuNcnkrnbMd2TrbOfdvf1PpyWJ8nqQEorWau0Aq0xppWe4gdzg==
  :verb: :get
:response:
  :status: 200
  :headers:
    server: nginx
    date: Wed, 05 Oct 2016 14:33:34 GMT
    content-type: application/json; charset=utf-8
    vary: Accept-Encoding
    x-ratelimit-limit: '100'
    x-ratelimit-remaining: '65'
    x-ratelimit-reset: '1475678040'
    x-frame-options: SAMEORIGIN
    x-xss-protection: 1; mode=block
    x-content-type-options: nosniff
    cache-control: max-age=300, private
    etag: W/"a008ffb0141ffc230812940672a946e5"
    x-request-id: '43076523'
    x-runtime: '0.045395'
    x-dns-prefetch-control: 'off'
    access-control-allow-origin: "*"
    access-control-allow-methods: HEAD, GET, POST, PUT, DELETE
    x-app: as1
    x-varnish: '43076522'
    age: '0'
    via: 1.1 varnish-v4
    x-origin: lb1
    x-cache: MISS
    x-cached: alve miss(0)
    accept-ranges: bytes
    transfer-encoding: chunked
    connection: close
  :body: '{"product":{"id":1135844,"name":"Samsung Galaxy S4 i9500 16Gb Siyah Cep
    Telefonu","sku_id":146414,"shop_id":77,"category_id":33,"availability":"Bilinmeyen
    Stok Durumu","click_url":"https://www.alve.com/products/show/1135844?client_id=a5DfUtj8w0fOy9gujmM8g%3D%3D\u0026from=api","shop_uid":"22374","expenses":null,"web_uri":"http://alve.com/products/show/1135844","sizes":[],"price":1155.24,"immediate_pickup":false}}'
:created_at: 2016-10-05 17:33:34.323734145 +03:00
