---
:request:
  :url: http://alve.com/api/products/1135844
  :headers:
    :accept: application/vnd.alve+json; version=3
    :authorization: Bearer yNE9qe8AC6yVbnVV8ofDPFiitoAREfqiq3THA6NYLQvUHbLHqlmUhHQ6kudbdrHa/0FlExa75mpN4PG/DEzSKw==
  :verb: GET
:response:
  :status: 200
  :headers:
    server: nginx
    !binary "Y29udGVudC10eXBl": application/json; charset=utf-8
    !binary "dmFyeQ==": Accept-Encoding
    status: 200 OK
    cache-control: max-age=300, private
    x-ua-compatible: IE=Edge,chrome=1
    x-request-id: '458392815'
    x-runtime: '0.043928'
    x-dns-prefetch-control: 'off'
    x-app: as2
    content-length: '243'
    accept-ranges: bytes
    date: Fri, 18 Jul 2014 15:17:37 GMT
    x-varnish: '458392815'
    age: '0'
    via: 1.1 varnish
    connection: close
    x-origin: varnish2
    x-cache: MISS
  :body: ! '{"product":{"id":1135844,"name":"Samsung Galaxy S4 / i9500 16 Gb Siyah
    Cep Telefonu","sku_id":146414,"shop_id":77,"category_id":33,"availability":null,"click_url":"https://www.alve.com/products/show/1135844?client_id=Bn9IVZbjL27QolcUwH1gA%3D%3D&from=api","price":1206.0}}'
:created_at: 2014-07-18 18:17:37.654983955 +03:00
