---
:request:
  :url: http://api.alve.com/shops/42/products/search?shop_uid=86711
  :headers:
    :accept: application/vnd.alve+json; version=3.1
    :authorization: Bearer Ei3DkEzs/gQSMk8EW8mPBJEyYPCliK7bvq1KhuNcnkrnbMd2TrbOfdvf1PpyWJ8nqQEorWau0Aq0xppWe4gdzg==
  :verb: :get
:response:
  :status: 200
  :headers:
    server: nginx
    date: Wed, 05 Oct 2016 14:33:34 GMT
    content-type: application/json; charset=utf-8
    vary: Accept-Encoding
    x-ratelimit-limit: '100'
    x-ratelimit-remaining: '64'
    x-ratelimit-reset: '1475678040'
    x-frame-options: SAMEORIGIN
    x-xss-protection: 1; mode=block
    x-content-type-options: nosniff
    etag: W/"fc1fc159029003b0f6d89b56fb4c821d"
    cache-control: max-age=0, private, must-revalidate
    x-request-id: '57564572'
    x-runtime: '0.025472'
    x-dns-prefetch-control: 'off'
    access-control-allow-origin: "*"
    access-control-allow-methods: HEAD, GET, POST, PUT, DELETE
    x-app: as1
    x-varnish: '57564571'
    age: '0'
    via: 1.1 varnish-v4
    x-origin: lb2
    x-cache: MISS
    x-cached: alve miss(0)
    accept-ranges: bytes
    content-length: '346'
    connection: close
  :body: '{"products":[{"id":497997,"name":"iPad Mini 16 GB Wi-fi Beyaz MD531","sku_id":75873,"shop_id":42,"category_id":19,"availability":"Bilinmeyen
    Stok Durumu","click_url":"https://www.alve.com/products/show/497997?client_id=a5DfUtj8w0fOy9gujmM8g%3D%3D\u0026from=api","shop_uid":"86711","expenses":5.31,"web_uri":"http://alve.com/products/show/497997","sizes":[],"price":707.13,"immediate_pickup":null}],"meta":{"pagination":{"total_results":1,"total_pages":1,"page":1,"per":25}}}'
:created_at: 2016-10-05 17:33:34.400043684 +03:00
