---
:request:
  :url: http://api.alve.com/products/1135844
  :headers:
    :accept: application/vnd.alve+json; version=3
    :authorization: Bearer jRc1LQwgl9wVf6QJT1hTfSL32I7V97Yta5fjEpDUHIDoPox/jRhUTe0K19DamN4NArCAy7tTrUyI8yXRxOVWg==
  :verb: GET
:response:
  :status: 200
  :headers:
    !binary "c2VydmVy": nginx
    !binary "Y29udGVudC10eXBl": application/json; charset=utf-8
    !binary "dmFyeQ==": Accept-Encoding
    !binary "c3RhdHVz": 200 OK
    !binary "Y2FjaGUtY29udHJvbA==": max-age=300, private
    !binary "eC11YS1jb21wYXRpYmxl": IE=Edge,chrome=1
    !binary "eC1yZXF1ZXN0LWlk": '984168102'
    !binary "eC1ydW50aW1l": '0.032219'
    !binary "eC1kbnMtcHJlZmV0Y2gtY29udHJvbA==": 'off'
    !binary "eC1hcHA=": as2
    !binary "Y29udGVudC1sZW5ndGg=": '243'
    !binary "YWNjZXB0LXJhbmdlcw==": bytes
    !binary "ZGF0ZQ==": Tue, 12 Aug 2014 09:16:24 GMT
    !binary "eC12YXJuaXNo": '984168102'
    !binary "YWdl": '0'
    !binary "dmlh": 1.1 varnish
    !binary "Y29ubmVjdGlvbg==": close
    !binary "eC1vcmlnaW4=": varnish1
    !binary "eC1jYWNoZQ==": MISS
  :body: ! '{"product":{"id":1135844,"name":"Samsung Galaxy S4 / i9500 16 Gb Siyah
    Cep Telefonu","sku_id":146414,"shop_id":77,"category_id":33,"availability":null,"click_url":"https://www.alve.com/products/show/1135844?client_id=Bn9IVZbjL27QolcUwH1gA%3D%3D&from=api","price":1206.0}}'
:created_at: 2014-08-12 12:16:24.216509958 +03:00
